zaksabeast/PokemonRNGGuides

- guides/usum/en/stationary wormhole.md
- guides/usum/en/stationary_wormhole.md
Add stationary guide
-USUM
Stationary
English
> Add stationary guide for USUM wormholes

- guides/frlg/en/stationary gift (emu).md
- FRLG
Stationary/Gift Guide
English
> Edited FRLG Stationary Guide

- guides/bw/en/roamers (emu).md
- Black, White
Roamers
English
Guide donated by /u/Zapdos44
> Add BW Roamer guide

- guides/sm/en/egg mm-sc.md
- guides/usum/en/egg mm-sc.md
> Add Gen 7 MM/SC Egg Guide

- guides/sm/en/egg mm-sc.md
- guides/usum/en/egg mm-sc.md
> Edited Gen 7 MM/SC Egg Guide

- guides/sm/en/island scan.md
- guides/usum/en/island scan.md
- SM
- USUM
- Island Scan
- English
> Minor edits to Gen 7 island scan guide

- guides/sm/en/island scan.md
- guides/usum/en/island scan.md
- SM
- USUM
- Island Scan
- English
> Minor edits to styling

- guides/frlg/en/wild (emu).md
> Minor edits to frlg wild guide

- guides/rse/en/RS TID RNG
- Ruby/Sapphire
- Dead Battery TID RNG
- English
> Adding Dead Battery RS TID RNG Guide

- guides/bw/en/entralink (emu).md
- Black, White
Entralink
English
Guide donated by /u/Zapdos44
> Add BW Entralink guide

- guides/tools/en/connect dolphin to vba.md
- None (Dolphin Emulator and VBA Emulator)
None (it's a tool guide)
English
Thanks to /u/Upper90175 for letting us use this guide!
> Add Dolphin to VBA connection guide

- PULL_REQUEST_TEMPLATE.md
- README.md
- guides/bw/en/entralink (emu).md
- guides/bw/en/roamers (emu).md
- black
- white
Credits to the original guide donators have been moved to the readme, and the PR template was updated to include a notes section.
> Move credits of original donators to readme

- guides/tools/en/transporter nature table.md
- Transporter
Describe the RNG - Transporter RNG
English
Wanted a header to span tables but couldn't get it to work. Added text above table instead
> /add/tools/en/natureconversiontable

- ISSUE_TEMPLATE.md
- guides/sm/en/timeline.md
- guides/tools/en/install pcalc.md
- guides/usum/en/timeline.md
- XY/ORAS
- SM/USUM
- Not an RNG guide, but needed for Gen 6/7 guides.
- English
> Added PCalc Installation Guide

- ISSUE_TEMPLATE.md
- guides/sm/en/timeline.md
- guides/usum/en/timeline.md
- None
- None
- English
- Added Issue Template
> Add Issue template

- guides/tools/en/install pcalc.md
- Tools
Describe the RNG - stationary, shadow, wild, egg, etc.
-English
If needed, please make small notes here for extra details.
> Update links and include Transporter PCalc.

- guides/sm/en/stationary.md
- guides/usum/en/stationary.md
- SM/USUM
- Stationary
- English
- Made edits to be consistent with the format of Gen 7 Wild RNG Guide. Also edited some sections for more details/info.
> Edit Gen 7 Stationary RNG Guide

- guides/tools/en/init-seed-stock.md
- Sun, Moon, Ultra Sun, Ultra Moon
- Method to find the initial seed for Gen 7 games using clock needles.
- English
-
> Tools: en: smusum: Initial seed with clocks (stock)

- guides/oras/en/tid-rng.md
- ORAS
- TID RNG
- English
- Made some minor edits and updated PCalc link.
> Edit ORAS TID RNG Guide

- guides/sm/en/mysterygift.md
- guides/usum/en/mysterygift.md
- SM/USUM
- Gen 7 Mystery Gift RNG
- English
> Add Gen 7 Mystery Gift Guide

- guides/sm/en/egg no masuda method-shiny charm.md
- guides/usum/en/egg no masuda method-shiny charm.md
- SM/USUM
- Eggs no MM/SC
- English
- Updated PCalc links, edited timeline section to refer to timeline guide instead, and other minor aesthetic and grammar edits.
> Updated Gen 7 Eggs No MM/SC Guides

- guides/sm/en/island scan.md
- guides/usum/en/island scan.md
- SM/USUM
- Island Scan
- English
> Updated links in Gen 7 Island Guides

- guides/sm/en/island scan.md
- guides/sm/en/stationary.md
- guides/usum/en/island scan.md
- guides/usum/en/stationary.md
- SM/USUM
- Stationary
- English
- Updated links and edited timeline section to refer to timeline guide
> Edited Gen 7 Stationary guides

- guides/sm/en/CFWless.md
- guides/usum/en/CFWless.md
- SM/USUM
- Gen 7 main RNG: Stationary, Event and Wild
- English
> Add CFWless guide

- Dream Radar RNG Guide.md
Pokemon Black 2 & Pokemon White 2
Dream Radar RNG guide on Emulator
English
N/A
> Dream Radar RNG Abuse Guide (EmuAbuse)

- guides/sm/en/find egg seeds-no cfw.md
- guides/usum/en/find egg seeds-no cfw.md
- SM/USUM
- Finding egg seeds without cfw/homebrew
- English
> Added Gen 7 guide to find egg seeds without cfw/homebrew

- guides/b2w2/en/Dream Radar RNG Guide.md
- BW2
- Dream Radar
- English
Made some small edits and changed formatting to display better on the site.
> Edited BW2 Dream Radar Guide

- How To Find DS Parameters in Generation 5 (EmuAbuse).md
Pokemon Black & White; Pokemon Black 2 & White 2
Walks the RNG'er through creating a profile for Generation 5 RNG.
English
N/A
> How To Find DS Parameters in Generation 5 (EmuAbuse)

- guides/usum/en/SOS RNG Guide.md
- USUM
- SOS RNG
- English
- Adding the guide after forgetting to stage change after renaming file previously.
> Adding Gen 7 SOS Guide

- guides/rse/en/Shiny WISHMKR Jirachi with wishmaker-calc (Emulator).md
- RSE
Shiny Wishmaker
English
This pull request makes a few tiny style changes.
> Minor formatting changes

- guides/oras/en/Egg RNG With Masuda Method or Shiny Charm.md
- guides/oras/en/Egg RNG Without Masuda Method or Shiny Charm.md
- guides/oras/en/TID RNG Guide.md
- guides/sm/en/Egg RNG With Masuda Method or Shiny Charm.md
- guides/sm/en/Egg RNG Without Masuda Method or Shiny Charm.md
- guides/sm/en/Island Scan RNG.md
- guides/sm/en/Mystery Gift (Event) RNG.md
- guides/sm/en/Stationary RNG.md
- guides/sm/en/Timeline Guide.md
- guides/sm/en/Wild RNG.md
- guides/tools/en/How to Install PCalc.md
- guides/usum/en/Egg RNG With Masuda Method or Shiny Charm.md
- guides/usum/en/Egg RNG Without Masuda Method or Shiny Charm.md
- guides/usum/en/Island Scan.md
- guides/usum/en/Mystery Gift (Event) RNG.md
- guides/usum/en/SOS RNG Guide.md
- guides/usum/en/Stationary RNG.md
- guides/usum/en/Stationary Wormhole RNG.md
- guides/usum/en/Timeline Guide.md
- guides/usum/en/Wild RNG.md
- guides/xy/en/Egg RNG With Masuda Method or Shiny Charm.md
- guides/xy/en/Egg RNG Without Masuda Method or Shiny Charm.md
- All Gen 6 and Gen 7 guides
- English
- Fixed all pcalc links to new website
> Edited pcalc links

- guides/usum/en/Egg RNG With Masuda Method or Shiny Charm.md
- guides/usum/en/Egg RNG Without Masuda Method or Shiny Charm.md
- guides/usum/en/How to Find Egg Seeds Without Custom Firmware.md
- guides/usum/en/Island Scan.md
- guides/usum/en/Mystery Gift (Event) RNG.md
- guides/usum/en/RNGing Without Custom Firmware.md
- guides/usum/en/SOS RNG Guide.md
- guides/usum/en/Stationary RNG.md
- guides/usum/en/Stationary Wormhole RNG.md
- guides/usum/en/Timeline Guide.md
- guides/usum/en/Timeline Leap Guide.md
- guides/usum/en/Wild RNG.md
This pull request adds consistency to Ultra Sun and Ultra Moon.
- Ultra Sun and Ultra Moon
English
> Add consistency to Ultra Sun and Ultra Moon

- guides/sm/en/Egg RNG With Masuda Method or Shiny Charm.md
- guides/sm/en/Egg RNG Without Masuda Method or Shiny Charm.md
- guides/sm/en/How to Find Egg Seeds Without Custom Firmware.md
- guides/sm/en/Island Scan RNG.md
- guides/sm/en/Mystery Gift (Event) RNG.md
- guides/sm/en/RNGing Without Custom Firmware.md
- guides/sm/en/Stationary RNG.md
- guides/sm/en/Timeline Guide.md
- guides/sm/en/Timeline Leap Guide.md
- guides/sm/en/Wild RNG.md
This pull request adds consistency to Sun and Moon.
- Sun and Moon
English
> Add consistency to Sun and Moon

- guides/oras/en/Egg RNG With Masuda Method or Shiny Charm.md
- guides/oras/en/Egg RNG Without Masuda Method or Shiny Charm.md
- guides/oras/en/TID RNG Guide.md
This pull request adds consistency to Omega Ruby and Alpha Sapphire.
- Omega Ruby and Alpha Sapphire
English
> Add consistency to Omega Ruby and Alpha Sapphire

- guides/xy/en/Egg RNG With Masuda Method or Shiny Charm.md
- guides/xy/en/Egg RNG Without Masuda Method or Shiny Charm.md
This pull request adds consistency to X and Y.
- X and Y
English
> Add consistency to X and Y

- guides/tools/en/Finding Initial Seed with Clocks (no Custom Firmware RNG).md
- guides/tools/en/How to Connect Dolphin to VBA.md
- guides/tools/en/How to Install PCalc.md
- guides/tools/en/Island Scan Pokemon - SM.md
- guides/tools/en/Island Scan Pokemon - USUM.md
- guides/tools/en/Transporter Nature Table.md
This pull request adds consistency to the tools guides.
- N/A
English
> Add consistency to the tools guides

- guides/hgss/en/Using Runasdate to RNG Initial Seed.md
This pull request adds consistency to Heart Gold and Soul Silver.
- Heart Gold and Soul Silver
English
> Add consistency to Heart Gold and Soul Silver

- guides/frlg/en/Stationary and Gift RNG (Emulator).md
- guides/frlg/en/Wild RNG (Emulator).md
This pull request adds consistency to Fire Red and Leaf Green.
- Fire Red and Leaf Green
English
> Add consistency to Fire Red and Leaf Green

- guides/dppt/en/Using Runasdate to RNG Initial Seed.md
This pull request adds consistency to Diamond, Pearl, and Platinum.
- Diamond, Pearl, and Platinum
English
> Add consistency Diamond, Pearl, and Platinum

- guides/b2w2/en/Dream Radar RNG Guide.md
- guides/b2w2/en/Using Runasdate to RNG Initial Seed.md
- guides/bw/en/Entralink RNG (Emulator).md
- guides/bw/en/Roamers (Emulator).md
- guides/bw/en/Using Runasdate to RNG Initial Seed.md
This pull request adds consistency to Gen 5 games.
- Black and White
- Black 2 and White 2
English
> Add consistency to Gen 5 games

- Example_Guide.md
This pull request updates the example guide.
> Update example guide

- guides/tools/en/How to Extract GBA Bios.md
- Gen 3 games
- Extracting the GBA.bios for use with emulator RNG
- ENG
> Extracting GBA Bios!!

- guides/rse/en/Shiny WISHMKR Jirachi with wishmaker-calc (Emulator).md
- guides/sm/en/Egg RNG Without Masuda Method or Shiny Charm.md
- guides/sm/en/How to Find Egg Seeds Without Custom Firmware.md
- guides/sm/en/Island Scan RNG.md
- guides/sm/en/Mystery Gift (Event) RNG.md
- guides/sm/en/RNGing Without Custom Firmware.md
- guides/sm/en/Stationary RNG.md
- guides/sm/en/Wild RNG.md
- guides/usum/en/Egg RNG Without Masuda Method or Shiny Charm.md
- guides/usum/en/How to Find Egg Seeds Without Custom Firmware.md
- guides/usum/en/Island Scan.md
- guides/usum/en/Mystery Gift (Event) RNG.md
- guides/usum/en/RNGing Without Custom Firmware.md
- guides/usum/en/SOS RNG Guide.md
- guides/usum/en/Stationary RNG.md
- guides/usum/en/Stationary Wormhole RNG.md
- guides/usum/en/Wild RNG.md
- RSE, SM, USUM
All
English
This pull request changes guide links to be directories.  This fixes some broken links on the site.
> Use directories for guide links

- guides/sm/en/Egg RNG With Masuda Method or Shiny Charm.md
- guides/sm/en/Egg RNG Without Masuda Method or Shiny Charm.md
- guides/usum/en/Egg RNG With Masuda Method or Shiny Charm.md
- guides/usum/en/Egg RNG Without Masuda Method or Shiny Charm.md
- SM/USUM
- Egg RNG with and without MM/SC
- English
- Edited the guides for grammar and spelling mistakes, and should be easier to understand.
> Edited Gen 7 Egg Guides

- guides/Black and White/Find DS Parameters.md
- Black/White
- Finding parameters
- English
> Edit Gen 5 DS Parameters

- guides/Sun and Moon/Timeline With Fidget Guide.md
- guides/Ultra Sun and Ultra Moon/Timeline With Fidget Guide.md
-Sun/Moon/Ultra Sun/Ultra Moon
- Timeline with character fidgeting
- English
> Add Gen 7 Timeline with Fidget Guides

- guides/Sun and Moon/Timeline Leap Guide.md
- guides/Ultra Sun and Ultra Moon/Timeline Leap Guide.md
PR to update Timeline Leap Guides since PR #131 was a mess to merge.
> Update timeline leap guides

- guides/FireRed and LeafGreen/Wild RNG.md
The Wild RNG guide for FireRed/LeafGreen has been updated to use the latest PokeFinder version and lua scripts from NOOB.
> Edit FireRed/LeafGreen Wild RNG

- guides/Citra and 3DS/CitraRNG Setup.md
This changes formatting in the CitraRNG guide to be consistent, and fix some formatting errors.
> Edit CitraRNG Guide

- src/components/guide-list.js
Guides will now be sorted alphabetically in each category.
> Sort guides alphabetically

- gatsby-config.js
- package.json
- src/components/footer.js
- yarn.lock
This will help with knowing when the site last deployed and which git commit it is using.
Added the gatsby plugin `gatsby-source-local-git` to accomplish this.
> Add latest git commit hash to footer

- guides/Black 2 and White 2/Using Runasdate to RNG Initial Seed.md
- guides/Black and White/Using Runasdate to RNG Initial Seed.md
The lua script links to Gen 5 instead of Gen 4 lua scripts. Also fixed some spelling mistakes and made other minor edits.
> Edit Gen 5 Initial Seed Guides

- gatsby-config.js
- package.json
- yarn.lock
This should now cache pages when viewed, and save them for viewing offline.
> Add offline support

- guides/Ruby and Sapphire/Egg RNG.md
Added a note about everstone and parents should not be holding any items.
> Edit Ruby and Sapphire Egg Guide

- src/pages/404.js
When trying to visit a link that does not exist, a custom 404 page will be displayed. Suggestions for how to improve the overall look are welcome.
Example:
> Create 404 (Not Found) Page

- guides/Tools and Emulators/CaptureSight Install.md
This PR adds a guide to installing CaptureSight for use with SwSh and BDSP RNG.
> Add CaptureSight install guide

- guides/Brilland Diamond annd Shining Pearl/Egg.md
> Fixed wording + added some helpful tips

- guides/Brilliant Diamond and Shining Pearl/Advancing the RNG.md
- src/utils/sort-categories.js
Adding a guide for how to advance the RNG in BDSP
> [Guide] Add BDSP Advancing the RNG Guide

- guides/Tools and Emulators/How to Install PokeReader.md
This is the beginning of replacing PokeCalc with PokeReader :tada:
> Add install PokeReader guide

- guides/Tools and Emulators/Transporter Patches.md
This adds an explanation for patches to be used with Transporter, all made by @zaksabeast <3
> Add Transporter Patches

- guides/Ruby and Sapphire/Live Battery TID RNG.mdx
This PR updates the Ruby/Sapphire Live Battery TID to use PokeFinder and the latest lua scripts from Real.
> Update Ruby/Sapphire Live Battery TID guide

- guides/Home.mdx
- index.html
- src/__generated__/guides.ts
Currently what can be reviewed:
- index.html: titles and descriptions
- home.mdx: homepage title, description, and intro
The rest of the home page is still a wip. I wanted to get your thoughts on what's already there before continuing.
> Update Home page

- guides/Gen 5/Roamers.mdx
- guides/Gen 6/Egg RNG With Masuda Method or Shiny Charm.mdx
- guides/Gen 6/Egg RNG Without Masuda Method or Shiny Charm.mdx
- guides/Gen 6/Friend Safari RNG Guide.mdx
- guides/Gen 7/Egg RNG With Masuda Method or Shiny Charm.mdx
- guides/Gen 7/Egg RNG Without Masuda Method or Shiny Charm.mdx
- guides/Gen 7/Island Scan.mdx
- guides/Gen 7/Mystery Gift.mdx
- guides/Gen 7/Stationary RNG.mdx
- guides/Gen 7/Stationary Wormhole RNG.mdx
- guides/Gen 7/Timeline Guide.mdx
- guides/Gen 7/Timeline Leap Guide.mdx
- guides/Gen 7/Timeline With Fidget Guide.mdx
- guides/Gen 7/Wild RNG.mdx
- guides/Transporter/Transporter with Offline Patch.mdx
- guides/Transporter/Transporter.mdx
This PR replaces PCalc for PokeReader in the relevant guides.
This closes #271.
> Replace PCalc with PokeReader

- guides/Sword and Shield/Raid RNG.mdx
Edited guide to be clearer and adjusted steps as needed.
> Update SwSh Raid Guide

- guides/Tools and Emulators/PokeFinder.mdx
- src/__generated__/guides.ts
This adds a general overview page for PokeFinder.
> Add PokeFinder Page

- guides/Transporter/Transporter.mdx
- rng_tools/src/generators/gen6/stationary.rs
- src/markdownExports/index.ts
- src/rngToolsUi/gen6/transporter/transporter.tsx
add files for typescript connections to add transporter
> TS for transporter generator

- guides/Tools and Emulators/Azahar Setup.mdx
- src/__generated__/guides.ts
Adds a page for dumping carts and updates for installing CIAs on Azahar.
> Azahar Setup Guide

- guides/Tools and Emulators/PokeReader.mdx
- src/__generated__/guides.ts
Needs images of PokeReader before being merged.
> Add PokeReader Page

- guides/Gen 2/Celebi.mdx
Added section to suggest Transporter RNG next.
Overall edits to the steps and tips for clarity.
> Edit Celebi Guide

- guides/Brilliant Diamond and Shining Pearl/BK - Emulator Setup.mdx
- src/__generated__/guides.ts
Updated links, moved it out of rough drafts, and edited for overall clarity.
> Edit BDSP Emulator Setup Guide

- guides/Gen 5/Using Runasdate to RNG Initial Seed.mdx
- guides/Gen 5/Wild RNG Emu.mdx
- guides/Gen 6/Egg RNG With Masuda Method or Shiny Charm.mdx
- guides/Gen 6/Egg RNG Without Masuda Method or Shiny Charm.mdx
- guides/Gen 7/Egg RNG Without Masuda Method or Shiny Charm.mdx
- guides/Gen 7/Finding Initial Seed with Clocks.mdx
- guides/Gen 7/How to Find Egg Seeds Without Custom Firmware.mdx
- guides/Gen 7/Island Scan.mdx
- guides/Gen 7/Mystery Gift.mdx
- guides/Gen 7/RNGing Without Custom Firmware.mdx
- guides/Gen 7/SOS RNG Guide.mdx
- guides/Gen 7/Stationary RNG.mdx
- guides/Gen 7/Time Finder.js (Citra).mdx
- guides/Gen 7/Timeline Guide.mdx
- guides/Gen 7/Timeline Leap Guide.mdx
- guides/Gen 7/Timeline With Fidget Guide.mdx
- guides/Gen 7/Wild RNG.mdx
Let me know if I missed any guides that should have a canonical link.
> Update canonical links

- guides/Brilliant Diamond and Shining Pearl/Advancing the RNG.mdx
- guides/Tools and Emulators/CaptureSight Install.mdx
- scripts/build-guides.ts
- src/__generated__/guides.ts
- src/components/languageButton.tsx
Translated CaptureSight installation guide and rng advance in BDSP to french.
Added the french  property and button to guide builder.
> adding a couple french translations

- guides/Gen 3/Emerald/GBA Methods Part2.mdx
- guides/Gen 3/Emerald/Gen 3 Wild.mdx
- rng_tools/src/generators/gen3/wild/calc_modulo_cycle_count.rs
- src/__generated__/guides.ts
- src/markdownExports/index.ts
- src/rngToolsUi/gen3/pidSpeedCalculator.tsx
- src/rngToolsUi/gen3/wild/wild3FindTarget.tsx
- src/utils/formatProbability.ts
> Lead PID Speed Calculator

- src/components/formFieldTable.tsx
- src/components/resultTable.tsx
```
const test1:Field = {
label:<Something />,
key:"something",
};  // no error
const test2:Field = {
label:"something",
};  // no error
const test3:Field = {
label:<Something />,
};  // error. key must be provided
```
> Add optional key prop on Column and Field, and support ReactNode title and label
